// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';
import 'api/frame_extractor.dart';
import 'api/simple.dart';
import 'api/xhs.dart';
import 'core/audio_error.dart';
import 'dart:async';
import 'dart:convert';
import 'frame_extractor/pipeline.dart';
import 'frame_extractor/state_machine.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models/xhs.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1069598482;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_cook_lib_exp',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  ExtractionStats crateApiFrameExtractorFrameExtractorManagerGetStats({
    required FrameExtractorManager that,
  });

  FrameExtractorManager crateApiFrameExtractorFrameExtractorManagerNew();

  Future<List<FrameExtractedInfo>>
  crateApiFrameExtractorFrameExtractorManagerProcessBatch({
    required FrameExtractorManager that,
    required List<YFrameData> frames,
  });

  FrameExtractedInfo? crateApiFrameExtractorFrameExtractorManagerProcessFrame({
    required FrameExtractorManager that,
    required int width,
    required int height,
    required List<int> rgbaData,
    required BigInt timestampMs,
    required BigInt frameNumber,
  });

  FrameExtractedInfo? crateApiFrameExtractorFrameExtractorManagerProcessYFrame({
    required FrameExtractorManager that,
    required int width,
    required int height,
    required List<int> yPlane,
    required BigInt timestampMs,
    required BigInt frameNumber,
  });

  FrameExtractedInfo?
  crateApiFrameExtractorFrameExtractorManagerProcessYuvFrame({
    required FrameExtractorManager that,
    required int width,
    required int height,
    required List<int> yPlane,
    required List<int> uPlane,
    required List<int> vPlane,
    required BigInt timestampMs,
    required BigInt frameNumber,
  });

  void crateApiFrameExtractorFrameExtractorManagerReset({
    required FrameExtractorManager that,
  });

  FrameExtractorManager
  crateApiFrameExtractorFrameExtractorManagerWithMockDetector({
    required Uint64List textFrames,
  });

  ExtractionConfig crateApiFrameExtractorCreateHighMotionConfig();

  ExtractionConfig crateApiFrameExtractorCreateLowMotionConfig();

  Future<List<CroppedFrame>> crateApiFrameExtractorCropAndResizeBatch({
    required List<YuvFrameData> frames,
    required FrameCropConfig config,
  });

  CroppedFrame crateApiFrameExtractorCropAndResizeFrame({
    required List<int> yPlane,
    required List<int> uPlane,
    required List<int> vPlane,
    required int width,
    required int height,
    required BigInt timestampMs,
    required BigInt frameNumber,
  });

  CroppedFrame crateApiFrameExtractorCropAndResizeFrameWithConfig({
    required List<int> yPlane,
    required List<int> uPlane,
    required List<int> vPlane,
    required int width,
    required int height,
    required BigInt timestampMs,
    required BigInt frameNumber,
    required FrameCropConfig config,
  });

  Future<FrameCropConfig> crateApiFrameExtractorFrameCropConfigDefault();

  String crateApiSimpleGreet({required String name});

  void crateApiAudioInitSherpa({required String modelPath});

  void crateApiAudioInitVad({required String vadModelPath});

  Future<void> crateApiSimpleInitApp();

  XhsArticle crateApiXhsParseXhsFromText({required String text});

  XhsArticle crateApiXhsParseXhsFromUrl({required String url});

  Future<String> crateApiAudioTranscribeAudio({
    required String path,
    String? language,
  });

  Future<String> crateApiAudioTranscribePcm({
    required List<double> pcm,
    required int sampleRate,
    String? language,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AudioErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FrameExtractorManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FrameExtractorManager;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FrameExtractorManagerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ExtractionStats crateApiFrameExtractorFrameExtractorManagerGetStats({
    required FrameExtractorManager that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_extraction_stats,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiFrameExtractorFrameExtractorManagerGetStatsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiFrameExtractorFrameExtractorManagerGetStatsConstMeta =>
      const TaskConstMeta(
        debugName: "FrameExtractorManager_get_stats",
        argNames: ["that"],
      );

  @override
  FrameExtractorManager crateApiFrameExtractorFrameExtractorManagerNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameExtractorFrameExtractorManagerNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrameExtractorFrameExtractorManagerNewConstMeta =>
      const TaskConstMeta(debugName: "FrameExtractorManager_new", argNames: []);

  @override
  Future<List<FrameExtractedInfo>>
  crateApiFrameExtractorFrameExtractorManagerProcessBatch({
    required FrameExtractorManager that,
    required List<YFrameData> frames,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
            that,
            serializer,
          );
          sse_encode_list_y_frame_data(frames, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_frame_extracted_info,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiFrameExtractorFrameExtractorManagerProcessBatchConstMeta,
        argValues: [that, frames],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiFrameExtractorFrameExtractorManagerProcessBatchConstMeta =>
      const TaskConstMeta(
        debugName: "FrameExtractorManager_process_batch",
        argNames: ["that", "frames"],
      );

  @override
  FrameExtractedInfo? crateApiFrameExtractorFrameExtractorManagerProcessFrame({
    required FrameExtractorManager that,
    required int width,
    required int height,
    required List<int> rgbaData,
    required BigInt timestampMs,
    required BigInt frameNumber,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
            that,
            serializer,
          );
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_list_prim_u_8_loose(rgbaData, serializer);
          sse_encode_u_64(timestampMs, serializer);
          sse_encode_u_64(frameNumber, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_frame_extracted_info,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiFrameExtractorFrameExtractorManagerProcessFrameConstMeta,
        argValues: [that, width, height, rgbaData, timestampMs, frameNumber],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiFrameExtractorFrameExtractorManagerProcessFrameConstMeta =>
      const TaskConstMeta(
        debugName: "FrameExtractorManager_process_frame",
        argNames: [
          "that",
          "width",
          "height",
          "rgbaData",
          "timestampMs",
          "frameNumber",
        ],
      );

  @override
  FrameExtractedInfo? crateApiFrameExtractorFrameExtractorManagerProcessYFrame({
    required FrameExtractorManager that,
    required int width,
    required int height,
    required List<int> yPlane,
    required BigInt timestampMs,
    required BigInt frameNumber,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
            that,
            serializer,
          );
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_list_prim_u_8_loose(yPlane, serializer);
          sse_encode_u_64(timestampMs, serializer);
          sse_encode_u_64(frameNumber, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_frame_extracted_info,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiFrameExtractorFrameExtractorManagerProcessYFrameConstMeta,
        argValues: [that, width, height, yPlane, timestampMs, frameNumber],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiFrameExtractorFrameExtractorManagerProcessYFrameConstMeta =>
      const TaskConstMeta(
        debugName: "FrameExtractorManager_process_y_frame",
        argNames: [
          "that",
          "width",
          "height",
          "yPlane",
          "timestampMs",
          "frameNumber",
        ],
      );

  @override
  FrameExtractedInfo?
  crateApiFrameExtractorFrameExtractorManagerProcessYuvFrame({
    required FrameExtractorManager that,
    required int width,
    required int height,
    required List<int> yPlane,
    required List<int> uPlane,
    required List<int> vPlane,
    required BigInt timestampMs,
    required BigInt frameNumber,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
            that,
            serializer,
          );
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_list_prim_u_8_loose(yPlane, serializer);
          sse_encode_list_prim_u_8_loose(uPlane, serializer);
          sse_encode_list_prim_u_8_loose(vPlane, serializer);
          sse_encode_u_64(timestampMs, serializer);
          sse_encode_u_64(frameNumber, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_frame_extracted_info,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiFrameExtractorFrameExtractorManagerProcessYuvFrameConstMeta,
        argValues: [
          that,
          width,
          height,
          yPlane,
          uPlane,
          vPlane,
          timestampMs,
          frameNumber,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiFrameExtractorFrameExtractorManagerProcessYuvFrameConstMeta =>
      const TaskConstMeta(
        debugName: "FrameExtractorManager_process_yuv_frame",
        argNames: [
          "that",
          "width",
          "height",
          "yPlane",
          "uPlane",
          "vPlane",
          "timestampMs",
          "frameNumber",
        ],
      );

  @override
  void crateApiFrameExtractorFrameExtractorManagerReset({
    required FrameExtractorManager that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameExtractorFrameExtractorManagerResetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiFrameExtractorFrameExtractorManagerResetConstMeta =>
      const TaskConstMeta(
        debugName: "FrameExtractorManager_reset",
        argNames: ["that"],
      );

  @override
  FrameExtractorManager
  crateApiFrameExtractorFrameExtractorManagerWithMockDetector({
    required Uint64List textFrames,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_64_strict(textFrames, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiFrameExtractorFrameExtractorManagerWithMockDetectorConstMeta,
        argValues: [textFrames],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiFrameExtractorFrameExtractorManagerWithMockDetectorConstMeta =>
      const TaskConstMeta(
        debugName: "FrameExtractorManager_with_mock_detector",
        argNames: ["textFrames"],
      );

  @override
  ExtractionConfig crateApiFrameExtractorCreateHighMotionConfig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_extraction_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameExtractorCreateHighMotionConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrameExtractorCreateHighMotionConfigConstMeta =>
      const TaskConstMeta(debugName: "create_high_motion_config", argNames: []);

  @override
  ExtractionConfig crateApiFrameExtractorCreateLowMotionConfig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_extraction_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameExtractorCreateLowMotionConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrameExtractorCreateLowMotionConfigConstMeta =>
      const TaskConstMeta(debugName: "create_low_motion_config", argNames: []);

  @override
  Future<List<CroppedFrame>> crateApiFrameExtractorCropAndResizeBatch({
    required List<YuvFrameData> frames,
    required FrameCropConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_yuv_frame_data(frames, serializer);
          sse_encode_box_autoadd_frame_crop_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_cropped_frame,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameExtractorCropAndResizeBatchConstMeta,
        argValues: [frames, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrameExtractorCropAndResizeBatchConstMeta =>
      const TaskConstMeta(
        debugName: "crop_and_resize_batch",
        argNames: ["frames", "config"],
      );

  @override
  CroppedFrame crateApiFrameExtractorCropAndResizeFrame({
    required List<int> yPlane,
    required List<int> uPlane,
    required List<int> vPlane,
    required int width,
    required int height,
    required BigInt timestampMs,
    required BigInt frameNumber,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(yPlane, serializer);
          sse_encode_list_prim_u_8_loose(uPlane, serializer);
          sse_encode_list_prim_u_8_loose(vPlane, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_64(timestampMs, serializer);
          sse_encode_u_64(frameNumber, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cropped_frame,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameExtractorCropAndResizeFrameConstMeta,
        argValues: [
          yPlane,
          uPlane,
          vPlane,
          width,
          height,
          timestampMs,
          frameNumber,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrameExtractorCropAndResizeFrameConstMeta =>
      const TaskConstMeta(
        debugName: "crop_and_resize_frame",
        argNames: [
          "yPlane",
          "uPlane",
          "vPlane",
          "width",
          "height",
          "timestampMs",
          "frameNumber",
        ],
      );

  @override
  CroppedFrame crateApiFrameExtractorCropAndResizeFrameWithConfig({
    required List<int> yPlane,
    required List<int> uPlane,
    required List<int> vPlane,
    required int width,
    required int height,
    required BigInt timestampMs,
    required BigInt frameNumber,
    required FrameCropConfig config,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(yPlane, serializer);
          sse_encode_list_prim_u_8_loose(uPlane, serializer);
          sse_encode_list_prim_u_8_loose(vPlane, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_64(timestampMs, serializer);
          sse_encode_u_64(frameNumber, serializer);
          sse_encode_box_autoadd_frame_crop_config(config, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cropped_frame,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameExtractorCropAndResizeFrameWithConfigConstMeta,
        argValues: [
          yPlane,
          uPlane,
          vPlane,
          width,
          height,
          timestampMs,
          frameNumber,
          config,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiFrameExtractorCropAndResizeFrameWithConfigConstMeta =>
      const TaskConstMeta(
        debugName: "crop_and_resize_frame_with_config",
        argNames: [
          "yPlane",
          "uPlane",
          "vPlane",
          "width",
          "height",
          "timestampMs",
          "frameNumber",
          "config",
        ],
      );

  @override
  Future<FrameCropConfig> crateApiFrameExtractorFrameCropConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frame_crop_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameExtractorFrameCropConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrameExtractorFrameCropConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "frame_crop_config_default", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  void crateApiAudioInitSherpa({required String modelPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError,
        ),
        constMeta: kCrateApiAudioInitSherpaConstMeta,
        argValues: [modelPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioInitSherpaConstMeta =>
      const TaskConstMeta(debugName: "initSherpa", argNames: ["modelPath"]);

  @override
  void crateApiAudioInitVad({required String vadModelPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vadModelPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError,
        ),
        constMeta: kCrateApiAudioInitVadConstMeta,
        argValues: [vadModelPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioInitVadConstMeta =>
      const TaskConstMeta(debugName: "initVad", argNames: ["vadModelPath"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  XhsArticle crateApiXhsParseXhsFromText({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xhs_article,
          decodeErrorData: sse_decode_xhs_api_error,
        ),
        constMeta: kCrateApiXhsParseXhsFromTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXhsParseXhsFromTextConstMeta =>
      const TaskConstMeta(debugName: "parse_xhs_from_text", argNames: ["text"]);

  @override
  XhsArticle crateApiXhsParseXhsFromUrl({required String url}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xhs_article,
          decodeErrorData: sse_decode_xhs_api_error,
        ),
        constMeta: kCrateApiXhsParseXhsFromUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXhsParseXhsFromUrlConstMeta =>
      const TaskConstMeta(debugName: "parse_xhs_from_url", argNames: ["url"]);

  @override
  Future<String> crateApiAudioTranscribeAudio({
    required String path,
    String? language,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_opt_String(language, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError,
        ),
        constMeta: kCrateApiAudioTranscribeAudioConstMeta,
        argValues: [path, language],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTranscribeAudioConstMeta =>
      const TaskConstMeta(
        debugName: "transcribeAudio",
        argNames: ["path", "language"],
      );

  @override
  Future<String> crateApiAudioTranscribePcm({
    required List<double> pcm,
    required int sampleRate,
    String? language,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(pcm, serializer);
          sse_encode_u_32(sampleRate, serializer);
          sse_encode_opt_String(language, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError,
        ),
        constMeta: kCrateApiAudioTranscribePcmConstMeta,
        argValues: [pcm, sampleRate, language],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioTranscribePcmConstMeta => const TaskConstMeta(
    debugName: "transcribePcm",
    argNames: ["pcm", "sampleRate", "language"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_FrameExtractorManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_FrameExtractorManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager;

  @protected
  AudioError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FrameExtractorManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FrameExtractorManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FrameExtractorManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FrameExtractorManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FrameExtractorManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FrameExtractorManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  FrameCropConfig dco_decode_box_autoadd_frame_crop_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frame_crop_config(raw);
  }

  @protected
  FrameExtractedInfo dco_decode_box_autoadd_frame_extracted_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_frame_extracted_info(raw);
  }

  @protected
  XhsVideo dco_decode_box_autoadd_xhs_video(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_xhs_video(raw);
  }

  @protected
  CroppedFrame dco_decode_cropped_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CroppedFrame(
      rgbData: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      timestampMs: dco_decode_u_64(arr[3]),
      frameNumber: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  ExtractionConfig dco_decode_extraction_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ExtractionConfig(
      stateConfig: dco_decode_state_config(arr[0]),
      diffThreshold: dco_decode_f_32(arr[1]),
      dedupThreshold: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  ExtractionStats dco_decode_extraction_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExtractionStats(
      processedFrames: dco_decode_u_64(arr[0]),
      extractedFrames: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrameCropConfig dco_decode_frame_crop_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FrameCropConfig(
      topCropRatio: dco_decode_f_32(arr[0]),
      bottomCropRatio: dco_decode_f_32(arr[1]),
      outputSize: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  FrameExtractedInfo dco_decode_frame_extracted_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FrameExtractedInfo(
      timestampMs: dco_decode_u_64(arr[0]),
      frameNumber: dco_decode_u_64(arr[1]),
      confidence: dco_decode_f_32(arr[2]),
      jpegData: dco_decode_list_prim_u_8_strict(arr[3]),
      width: dco_decode_u_32(arr[4]),
      height: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CroppedFrame> dco_decode_list_cropped_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cropped_frame).toList();
  }

  @protected
  List<FrameExtractedInfo> dco_decode_list_frame_extracted_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frame_extracted_info).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<YFrameData> dco_decode_list_y_frame_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_y_frame_data).toList();
  }

  @protected
  List<YuvFrameData> dco_decode_list_yuv_frame_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_yuv_frame_data).toList();
  }

  @protected
  NoteType dco_decode_note_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NoteType.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FrameExtractedInfo? dco_decode_opt_box_autoadd_frame_extracted_info(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_frame_extracted_info(raw);
  }

  @protected
  XhsVideo? dco_decode_opt_box_autoadd_xhs_video(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_xhs_video(raw);
  }

  @protected
  StateConfig dco_decode_state_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StateConfig(
      initialSkip: dco_decode_u_32(arr[0]),
      maxSkip: dco_decode_u_32(arr[1]),
      minLockFrames: dco_decode_u_32(arr[2]),
      cooldownFrames: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  XhsApiError dco_decode_xhs_api_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return XhsApiError(
      errorType: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  XhsArticle dco_decode_xhs_article(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return XhsArticle(
      title: dco_decode_String(arr[0]),
      desc: dco_decode_String(arr[1]),
      author: dco_decode_xhs_author(arr[2]),
      images: dco_decode_list_String(arr[3]),
      video: dco_decode_opt_box_autoadd_xhs_video(arr[4]),
      noteType: dco_decode_note_type(arr[5]),
    );
  }

  @protected
  XhsAuthor dco_decode_xhs_author(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return XhsAuthor(
      nickname: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
      avatar: dco_decode_String(arr[2]),
    );
  }

  @protected
  XhsVideo dco_decode_xhs_video(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return XhsVideo(
      duration: dco_decode_i_64(arr[0]),
      cover: dco_decode_String(arr[1]),
      playUrl: dco_decode_String(arr[2]),
    );
  }

  @protected
  YFrameData dco_decode_y_frame_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return YFrameData(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      yPlane: dco_decode_list_prim_u_8_strict(arr[2]),
      timestampMs: dco_decode_u_64(arr[3]),
      frameNumber: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  YuvFrameData dco_decode_yuv_frame_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return YuvFrameData(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      yPlane: dco_decode_list_prim_u_8_strict(arr[2]),
      uPlane: dco_decode_list_prim_u_8_strict(arr[3]),
      vPlane: dco_decode_list_prim_u_8_strict(arr[4]),
      timestampMs: dco_decode_u_64(arr[5]),
      frameNumber: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  AudioError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FrameExtractorManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FrameExtractorManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FrameExtractorManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FrameExtractorManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  FrameExtractorManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FrameExtractorManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  FrameCropConfig sse_decode_box_autoadd_frame_crop_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frame_crop_config(deserializer));
  }

  @protected
  FrameExtractedInfo sse_decode_box_autoadd_frame_extracted_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_frame_extracted_info(deserializer));
  }

  @protected
  XhsVideo sse_decode_box_autoadd_xhs_video(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_xhs_video(deserializer));
  }

  @protected
  CroppedFrame sse_decode_cropped_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rgbData = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_frameNumber = sse_decode_u_64(deserializer);
    return CroppedFrame(
      rgbData: var_rgbData,
      width: var_width,
      height: var_height,
      timestampMs: var_timestampMs,
      frameNumber: var_frameNumber,
    );
  }

  @protected
  ExtractionConfig sse_decode_extraction_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stateConfig = sse_decode_state_config(deserializer);
    var var_diffThreshold = sse_decode_f_32(deserializer);
    var var_dedupThreshold = sse_decode_u_32(deserializer);
    return ExtractionConfig(
      stateConfig: var_stateConfig,
      diffThreshold: var_diffThreshold,
      dedupThreshold: var_dedupThreshold,
    );
  }

  @protected
  ExtractionStats sse_decode_extraction_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_processedFrames = sse_decode_u_64(deserializer);
    var var_extractedFrames = sse_decode_u_64(deserializer);
    return ExtractionStats(
      processedFrames: var_processedFrames,
      extractedFrames: var_extractedFrames,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FrameCropConfig sse_decode_frame_crop_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_topCropRatio = sse_decode_f_32(deserializer);
    var var_bottomCropRatio = sse_decode_f_32(deserializer);
    var var_outputSize = sse_decode_u_32(deserializer);
    return FrameCropConfig(
      topCropRatio: var_topCropRatio,
      bottomCropRatio: var_bottomCropRatio,
      outputSize: var_outputSize,
    );
  }

  @protected
  FrameExtractedInfo sse_decode_frame_extracted_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_frameNumber = sse_decode_u_64(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    var var_jpegData = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return FrameExtractedInfo(
      timestampMs: var_timestampMs,
      frameNumber: var_frameNumber,
      confidence: var_confidence,
      jpegData: var_jpegData,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CroppedFrame> sse_decode_list_cropped_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CroppedFrame>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cropped_frame(deserializer));
    }
    return ans_;
  }

  @protected
  List<FrameExtractedInfo> sse_decode_list_frame_extracted_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FrameExtractedInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frame_extracted_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<YFrameData> sse_decode_list_y_frame_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <YFrameData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_y_frame_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<YuvFrameData> sse_decode_list_yuv_frame_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <YuvFrameData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_yuv_frame_data(deserializer));
    }
    return ans_;
  }

  @protected
  NoteType sse_decode_note_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NoteType.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FrameExtractedInfo? sse_decode_opt_box_autoadd_frame_extracted_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_frame_extracted_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  XhsVideo? sse_decode_opt_box_autoadd_xhs_video(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_xhs_video(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StateConfig sse_decode_state_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_initialSkip = sse_decode_u_32(deserializer);
    var var_maxSkip = sse_decode_u_32(deserializer);
    var var_minLockFrames = sse_decode_u_32(deserializer);
    var var_cooldownFrames = sse_decode_u_32(deserializer);
    return StateConfig(
      initialSkip: var_initialSkip,
      maxSkip: var_maxSkip,
      minLockFrames: var_minLockFrames,
      cooldownFrames: var_cooldownFrames,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  XhsApiError sse_decode_xhs_api_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_errorType = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return XhsApiError(errorType: var_errorType, message: var_message);
  }

  @protected
  XhsArticle sse_decode_xhs_article(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_desc = sse_decode_String(deserializer);
    var var_author = sse_decode_xhs_author(deserializer);
    var var_images = sse_decode_list_String(deserializer);
    var var_video = sse_decode_opt_box_autoadd_xhs_video(deserializer);
    var var_noteType = sse_decode_note_type(deserializer);
    return XhsArticle(
      title: var_title,
      desc: var_desc,
      author: var_author,
      images: var_images,
      video: var_video,
      noteType: var_noteType,
    );
  }

  @protected
  XhsAuthor sse_decode_xhs_author(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nickname = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_avatar = sse_decode_String(deserializer);
    return XhsAuthor(
      nickname: var_nickname,
      userId: var_userId,
      avatar: var_avatar,
    );
  }

  @protected
  XhsVideo sse_decode_xhs_video(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_duration = sse_decode_i_64(deserializer);
    var var_cover = sse_decode_String(deserializer);
    var var_playUrl = sse_decode_String(deserializer);
    return XhsVideo(
      duration: var_duration,
      cover: var_cover,
      playUrl: var_playUrl,
    );
  }

  @protected
  YFrameData sse_decode_y_frame_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_yPlane = sse_decode_list_prim_u_8_strict(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_frameNumber = sse_decode_u_64(deserializer);
    return YFrameData(
      width: var_width,
      height: var_height,
      yPlane: var_yPlane,
      timestampMs: var_timestampMs,
      frameNumber: var_frameNumber,
    );
  }

  @protected
  YuvFrameData sse_decode_yuv_frame_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_yPlane = sse_decode_list_prim_u_8_strict(deserializer);
    var var_uPlane = sse_decode_list_prim_u_8_strict(deserializer);
    var var_vPlane = sse_decode_list_prim_u_8_strict(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_frameNumber = sse_decode_u_64(deserializer);
    return YuvFrameData(
      width: var_width,
      height: var_height,
      yPlane: var_yPlane,
      uPlane: var_uPlane,
      vPlane: var_vPlane,
      timestampMs: var_timestampMs,
      frameNumber: var_frameNumber,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    AudioError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    FrameExtractorManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FrameExtractorManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    FrameExtractorManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FrameExtractorManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    AudioError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    FrameExtractorManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as FrameExtractorManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_frame_crop_config(
    FrameCropConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frame_crop_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_frame_extracted_info(
    FrameExtractedInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_frame_extracted_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_xhs_video(
    XhsVideo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_xhs_video(self, serializer);
  }

  @protected
  void sse_encode_cropped_frame(CroppedFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.rgbData, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_u_64(self.frameNumber, serializer);
  }

  @protected
  void sse_encode_extraction_config(
    ExtractionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_state_config(self.stateConfig, serializer);
    sse_encode_f_32(self.diffThreshold, serializer);
    sse_encode_u_32(self.dedupThreshold, serializer);
  }

  @protected
  void sse_encode_extraction_stats(
    ExtractionStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.processedFrames, serializer);
    sse_encode_u_64(self.extractedFrames, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_frame_crop_config(
    FrameCropConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.topCropRatio, serializer);
    sse_encode_f_32(self.bottomCropRatio, serializer);
    sse_encode_u_32(self.outputSize, serializer);
  }

  @protected
  void sse_encode_frame_extracted_info(
    FrameExtractedInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_u_64(self.frameNumber, serializer);
    sse_encode_f_32(self.confidence, serializer);
    sse_encode_list_prim_u_8_strict(self.jpegData, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_cropped_frame(
    List<CroppedFrame> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cropped_frame(item, serializer);
    }
  }

  @protected
  void sse_encode_list_frame_extracted_info(
    List<FrameExtractedInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frame_extracted_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_y_frame_data(
    List<YFrameData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_y_frame_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_yuv_frame_data(
    List<YuvFrameData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_yuv_frame_data(item, serializer);
    }
  }

  @protected
  void sse_encode_note_type(NoteType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_frame_extracted_info(
    FrameExtractedInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_frame_extracted_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_xhs_video(
    XhsVideo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_xhs_video(self, serializer);
    }
  }

  @protected
  void sse_encode_state_config(StateConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.initialSkip, serializer);
    sse_encode_u_32(self.maxSkip, serializer);
    sse_encode_u_32(self.minLockFrames, serializer);
    sse_encode_u_32(self.cooldownFrames, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_xhs_api_error(XhsApiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.errorType, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_xhs_article(XhsArticle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.desc, serializer);
    sse_encode_xhs_author(self.author, serializer);
    sse_encode_list_String(self.images, serializer);
    sse_encode_opt_box_autoadd_xhs_video(self.video, serializer);
    sse_encode_note_type(self.noteType, serializer);
  }

  @protected
  void sse_encode_xhs_author(XhsAuthor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nickname, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.avatar, serializer);
  }

  @protected
  void sse_encode_xhs_video(XhsVideo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.duration, serializer);
    sse_encode_String(self.cover, serializer);
    sse_encode_String(self.playUrl, serializer);
  }

  @protected
  void sse_encode_y_frame_data(YFrameData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.yPlane, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_u_64(self.frameNumber, serializer);
  }

  @protected
  void sse_encode_yuv_frame_data(YuvFrameData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.yPlane, serializer);
    sse_encode_list_prim_u_8_strict(self.uPlane, serializer);
    sse_encode_list_prim_u_8_strict(self.vPlane, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_u_64(self.frameNumber, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AudioErrorImpl extends RustOpaque implements AudioError {
  // Not to be used by end users
  AudioErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AudioErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AudioError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioErrorPtr,
  );
}

@sealed
class FrameExtractorManagerImpl extends RustOpaque
    implements FrameExtractorManager {
  // Not to be used by end users
  FrameExtractorManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FrameExtractorManagerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_FrameExtractorManager,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FrameExtractorManager,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_FrameExtractorManagerPtr,
  );

  ExtractionStats getStats() => RustLib.instance.api
      .crateApiFrameExtractorFrameExtractorManagerGetStats(that: this);

  /// 异步批量处理 - 智能文字状态去重
  /// 策略：先裁剪缩放，再判断"有没有文字"，再判断"文字变没变"
  Future<List<FrameExtractedInfo>> processBatch({
    required List<YFrameData> frames,
  }) => RustLib.instance.api
      .crateApiFrameExtractorFrameExtractorManagerProcessBatch(
        that: this,
        frames: frames,
      );

  FrameExtractedInfo? processFrame({
    required int width,
    required int height,
    required List<int> rgbaData,
    required BigInt timestampMs,
    required BigInt frameNumber,
  }) => RustLib.instance.api
      .crateApiFrameExtractorFrameExtractorManagerProcessFrame(
        that: this,
        width: width,
        height: height,
        rgbaData: rgbaData,
        timestampMs: timestampMs,
        frameNumber: frameNumber,
      );

  FrameExtractedInfo? processYFrame({
    required int width,
    required int height,
    required List<int> yPlane,
    required BigInt timestampMs,
    required BigInt frameNumber,
  }) => RustLib.instance.api
      .crateApiFrameExtractorFrameExtractorManagerProcessYFrame(
        that: this,
        width: width,
        height: height,
        yPlane: yPlane,
        timestampMs: timestampMs,
        frameNumber: frameNumber,
      );

  FrameExtractedInfo? processYuvFrame({
    required int width,
    required int height,
    required List<int> yPlane,
    required List<int> uPlane,
    required List<int> vPlane,
    required BigInt timestampMs,
    required BigInt frameNumber,
  }) => RustLib.instance.api
      .crateApiFrameExtractorFrameExtractorManagerProcessYuvFrame(
        that: this,
        width: width,
        height: height,
        yPlane: yPlane,
        uPlane: uPlane,
        vPlane: vPlane,
        timestampMs: timestampMs,
        frameNumber: frameNumber,
      );

  void reset() => RustLib.instance.api
      .crateApiFrameExtractorFrameExtractorManagerReset(that: this);
}
