// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';
import 'api/frame_extractor.dart';
import 'api/simple.dart';
import 'api/xhs.dart';
import 'core/audio_error.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frame_extractor/pipeline.dart';
import 'frame_extractor/state_machine.dart';
import 'frb_generated.dart';
import 'models/xhs.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AudioErrorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioErrorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FrameExtractorManagerPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManagerPtr;

  @protected
  AudioError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    dynamic raw,
  );

  @protected
  FrameExtractorManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    dynamic raw,
  );

  @protected
  FrameExtractorManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    dynamic raw,
  );

  @protected
  AudioError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    dynamic raw,
  );

  @protected
  FrameExtractorManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  FrameCropConfig dco_decode_box_autoadd_frame_crop_config(dynamic raw);

  @protected
  FrameExtractedInfo dco_decode_box_autoadd_frame_extracted_info(dynamic raw);

  @protected
  XhsVideo dco_decode_box_autoadd_xhs_video(dynamic raw);

  @protected
  CroppedFrame dco_decode_cropped_frame(dynamic raw);

  @protected
  ExtractionConfig dco_decode_extraction_config(dynamic raw);

  @protected
  ExtractionStats dco_decode_extraction_stats(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FrameCropConfig dco_decode_frame_crop_config(dynamic raw);

  @protected
  FrameExtractedInfo dco_decode_frame_extracted_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CroppedFrame> dco_decode_list_cropped_frame(dynamic raw);

  @protected
  List<FrameExtractedInfo> dco_decode_list_frame_extracted_info(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<YFrameData> dco_decode_list_y_frame_data(dynamic raw);

  @protected
  List<YuvFrameData> dco_decode_list_yuv_frame_data(dynamic raw);

  @protected
  NoteType dco_decode_note_type(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FrameExtractedInfo? dco_decode_opt_box_autoadd_frame_extracted_info(
    dynamic raw,
  );

  @protected
  XhsVideo? dco_decode_opt_box_autoadd_xhs_video(dynamic raw);

  @protected
  StateConfig dco_decode_state_config(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  XhsApiError dco_decode_xhs_api_error(dynamic raw);

  @protected
  XhsArticle dco_decode_xhs_article(dynamic raw);

  @protected
  XhsAuthor dco_decode_xhs_author(dynamic raw);

  @protected
  XhsVideo dco_decode_xhs_video(dynamic raw);

  @protected
  YFrameData dco_decode_y_frame_data(dynamic raw);

  @protected
  YuvFrameData dco_decode_yuv_frame_data(dynamic raw);

  @protected
  AudioError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    SseDeserializer deserializer,
  );

  @protected
  FrameExtractorManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    SseDeserializer deserializer,
  );

  @protected
  FrameExtractorManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    SseDeserializer deserializer,
  );

  @protected
  AudioError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    SseDeserializer deserializer,
  );

  @protected
  FrameExtractorManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  FrameCropConfig sse_decode_box_autoadd_frame_crop_config(
    SseDeserializer deserializer,
  );

  @protected
  FrameExtractedInfo sse_decode_box_autoadd_frame_extracted_info(
    SseDeserializer deserializer,
  );

  @protected
  XhsVideo sse_decode_box_autoadd_xhs_video(SseDeserializer deserializer);

  @protected
  CroppedFrame sse_decode_cropped_frame(SseDeserializer deserializer);

  @protected
  ExtractionConfig sse_decode_extraction_config(SseDeserializer deserializer);

  @protected
  ExtractionStats sse_decode_extraction_stats(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FrameCropConfig sse_decode_frame_crop_config(SseDeserializer deserializer);

  @protected
  FrameExtractedInfo sse_decode_frame_extracted_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CroppedFrame> sse_decode_list_cropped_frame(
    SseDeserializer deserializer,
  );

  @protected
  List<FrameExtractedInfo> sse_decode_list_frame_extracted_info(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<YFrameData> sse_decode_list_y_frame_data(SseDeserializer deserializer);

  @protected
  List<YuvFrameData> sse_decode_list_yuv_frame_data(
    SseDeserializer deserializer,
  );

  @protected
  NoteType sse_decode_note_type(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FrameExtractedInfo? sse_decode_opt_box_autoadd_frame_extracted_info(
    SseDeserializer deserializer,
  );

  @protected
  XhsVideo? sse_decode_opt_box_autoadd_xhs_video(SseDeserializer deserializer);

  @protected
  StateConfig sse_decode_state_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  XhsApiError sse_decode_xhs_api_error(SseDeserializer deserializer);

  @protected
  XhsArticle sse_decode_xhs_article(SseDeserializer deserializer);

  @protected
  XhsAuthor sse_decode_xhs_author(SseDeserializer deserializer);

  @protected
  XhsVideo sse_decode_xhs_video(SseDeserializer deserializer);

  @protected
  YFrameData sse_decode_y_frame_data(SseDeserializer deserializer);

  @protected
  YuvFrameData sse_decode_yuv_frame_data(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    AudioError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    FrameExtractorManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    FrameExtractorManager self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    AudioError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    FrameExtractorManager self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frame_crop_config(
    FrameCropConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frame_extracted_info(
    FrameExtractedInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_xhs_video(
    XhsVideo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cropped_frame(CroppedFrame self, SseSerializer serializer);

  @protected
  void sse_encode_extraction_config(
    ExtractionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_extraction_stats(
    ExtractionStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_frame_crop_config(
    FrameCropConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frame_extracted_info(
    FrameExtractedInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cropped_frame(
    List<CroppedFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frame_extracted_info(
    List<FrameExtractedInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_y_frame_data(
    List<YFrameData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_yuv_frame_data(
    List<YuvFrameData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_type(NoteType self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_frame_extracted_info(
    FrameExtractedInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_xhs_video(
    XhsVideo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_state_config(StateConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_xhs_api_error(XhsApiError self, SseSerializer serializer);

  @protected
  void sse_encode_xhs_article(XhsArticle self, SseSerializer serializer);

  @protected
  void sse_encode_xhs_author(XhsAuthor self, SseSerializer serializer);

  @protected
  void sse_encode_xhs_video(XhsVideo self, SseSerializer serializer);

  @protected
  void sse_encode_y_frame_data(YFrameData self, SseSerializer serializer);

  @protected
  void sse_encode_yuv_frame_data(YuvFrameData self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_cook_lib_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_cook_lib_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManagerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_cook_lib_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManagerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManagerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_cook_lib_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManager =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFrameExtractorManagerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
