// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';
import 'api/models/xhs.dart';
import 'api/video.dart';
import 'api/xhs.dart';
import 'core/audio/error.dart';
import 'core/video/manager.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -223892292;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cook_lib',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AudioRecognizer> crateApiAudioAudioRecognizerCreate({
    required String modelsDir,
  });

  String crateApiAudioAudioRecognizerModelsDir({required AudioRecognizer that});

  Future<String> crateApiAudioAudioRecognizerTranscribeAudio({
    required AudioRecognizer that,
    required String path,
    String? language,
  });

  VideoFrameExtractor crateApiVideoVideoFrameExtractorCreate();

  Future<List<FrameExtractedInfo>>
  crateApiVideoVideoFrameExtractorProcessBatch({
    required VideoFrameExtractor that,
    required List<YFrameData> frames,
  });

  void crateApiVideoVideoFrameExtractorReset({
    required VideoFrameExtractor that,
  });

  ExtractionStats crateApiVideoVideoFrameExtractorStats({
    required VideoFrameExtractor that,
  });

  Future<NoteType> crateApiModelsXhsNoteTypeDefault();

  XhsArticle crateApiXhsParseXhsFromText({required String text});

  XhsArticle crateApiXhsParseXhsFromUrl({required String url});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AudioErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioRecognizer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioRecognizer;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AudioRecognizerPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VideoFrameExtractor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VideoFrameExtractor;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_VideoFrameExtractorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AudioRecognizer> crateApiAudioAudioRecognizerCreate({
    required String modelsDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelsDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError,
        ),
        constMeta: kCrateApiAudioAudioRecognizerCreateConstMeta,
        argValues: [modelsDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioRecognizerCreateConstMeta =>
      const TaskConstMeta(
        debugName: "AudioRecognizer_create",
        argNames: ["modelsDir"],
      );

  @override
  String crateApiAudioAudioRecognizerModelsDir({
    required AudioRecognizer that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioAudioRecognizerModelsDirConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioRecognizerModelsDirConstMeta =>
      const TaskConstMeta(
        debugName: "AudioRecognizer_models_dir",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiAudioAudioRecognizerTranscribeAudio({
    required AudioRecognizer that,
    required String path,
    String? language,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          sse_encode_opt_String(language, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError,
        ),
        constMeta: kCrateApiAudioAudioRecognizerTranscribeAudioConstMeta,
        argValues: [that, path, language],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioRecognizerTranscribeAudioConstMeta =>
      const TaskConstMeta(
        debugName: "AudioRecognizer_transcribe_audio",
        argNames: ["that", "path", "language"],
      );

  @override
  VideoFrameExtractor crateApiVideoVideoFrameExtractorCreate() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVideoVideoFrameExtractorCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoVideoFrameExtractorCreateConstMeta =>
      const TaskConstMeta(
        debugName: "VideoFrameExtractor_create",
        argNames: [],
      );

  @override
  Future<List<FrameExtractedInfo>>
  crateApiVideoVideoFrameExtractorProcessBatch({
    required VideoFrameExtractor that,
    required List<YFrameData> frames,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
            that,
            serializer,
          );
          sse_encode_list_y_frame_data(frames, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_frame_extracted_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVideoVideoFrameExtractorProcessBatchConstMeta,
        argValues: [that, frames],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoVideoFrameExtractorProcessBatchConstMeta =>
      const TaskConstMeta(
        debugName: "VideoFrameExtractor_process_batch",
        argNames: ["that", "frames"],
      );

  @override
  void crateApiVideoVideoFrameExtractorReset({
    required VideoFrameExtractor that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVideoVideoFrameExtractorResetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoVideoFrameExtractorResetConstMeta =>
      const TaskConstMeta(
        debugName: "VideoFrameExtractor_reset",
        argNames: ["that"],
      );

  @override
  ExtractionStats crateApiVideoVideoFrameExtractorStats({
    required VideoFrameExtractor that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_extraction_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVideoVideoFrameExtractorStatsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoVideoFrameExtractorStatsConstMeta =>
      const TaskConstMeta(
        debugName: "VideoFrameExtractor_stats",
        argNames: ["that"],
      );

  @override
  Future<NoteType> crateApiModelsXhsNoteTypeDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_type,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelsXhsNoteTypeDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsXhsNoteTypeDefaultConstMeta =>
      const TaskConstMeta(debugName: "note_type_default", argNames: []);

  @override
  XhsArticle crateApiXhsParseXhsFromText({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xhs_article,
          decodeErrorData: sse_decode_xhs_api_error,
        ),
        constMeta: kCrateApiXhsParseXhsFromTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXhsParseXhsFromTextConstMeta =>
      const TaskConstMeta(debugName: "parse_xhs_from_text", argNames: ["text"]);

  @override
  XhsArticle crateApiXhsParseXhsFromUrl({required String url}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xhs_article,
          decodeErrorData: sse_decode_xhs_api_error,
        ),
        constMeta: kCrateApiXhsParseXhsFromUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXhsParseXhsFromUrlConstMeta =>
      const TaskConstMeta(debugName: "parse_xhs_from_url", argNames: ["url"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AudioRecognizer => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AudioRecognizer => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_VideoFrameExtractor => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_VideoFrameExtractor => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor;

  @protected
  AudioError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioRecognizer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioRecognizerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VideoFrameExtractor
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoFrameExtractorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioRecognizer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioRecognizerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VideoFrameExtractor
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoFrameExtractorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AudioRecognizer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AudioRecognizerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VideoFrameExtractor
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoFrameExtractorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  XhsVideo dco_decode_box_autoadd_xhs_video(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_xhs_video(raw);
  }

  @protected
  ExtractionStats dco_decode_extraction_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExtractionStats(
      processedFrames: dco_decode_u_64(arr[0]),
      extractedFrames: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrameExtractedInfo dco_decode_frame_extracted_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FrameExtractedInfo(
      timestampMs: dco_decode_u_64(arr[0]),
      frameNumber: dco_decode_u_64(arr[1]),
      confidence: dco_decode_f_32(arr[2]),
      jpegData: dco_decode_list_prim_u_8_strict(arr[3]),
      width: dco_decode_u_32(arr[4]),
      height: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FrameExtractedInfo> dco_decode_list_frame_extracted_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frame_extracted_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<YFrameData> dco_decode_list_y_frame_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_y_frame_data).toList();
  }

  @protected
  NoteType dco_decode_note_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NoteType.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  XhsVideo? dco_decode_opt_box_autoadd_xhs_video(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_xhs_video(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  XhsApiError dco_decode_xhs_api_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return XhsApiError(
      errorType: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  XhsArticle dco_decode_xhs_article(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return XhsArticle(
      title: dco_decode_String(arr[0]),
      desc: dco_decode_String(arr[1]),
      author: dco_decode_xhs_author(arr[2]),
      images: dco_decode_list_String(arr[3]),
      video: dco_decode_opt_box_autoadd_xhs_video(arr[4]),
      noteType: dco_decode_note_type(arr[5]),
    );
  }

  @protected
  XhsAuthor dco_decode_xhs_author(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return XhsAuthor(
      nickname: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
      avatar: dco_decode_String(arr[2]),
    );
  }

  @protected
  XhsVideo dco_decode_xhs_video(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return XhsVideo(
      duration: dco_decode_i_64(arr[0]),
      cover: dco_decode_String(arr[1]),
      playUrl: dco_decode_String(arr[2]),
    );
  }

  @protected
  YFrameData dco_decode_y_frame_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return YFrameData(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      yPlane: dco_decode_list_prim_u_8_strict(arr[2]),
      timestampMs: dco_decode_u_64(arr[3]),
      frameNumber: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  AudioError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioRecognizer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioRecognizerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VideoFrameExtractor
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VideoFrameExtractorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioRecognizer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioRecognizerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VideoFrameExtractor
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VideoFrameExtractorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AudioRecognizer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AudioRecognizerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  VideoFrameExtractor
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VideoFrameExtractorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  XhsVideo sse_decode_box_autoadd_xhs_video(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_xhs_video(deserializer));
  }

  @protected
  ExtractionStats sse_decode_extraction_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_processedFrames = sse_decode_u_64(deserializer);
    var var_extractedFrames = sse_decode_u_64(deserializer);
    return ExtractionStats(
      processedFrames: var_processedFrames,
      extractedFrames: var_extractedFrames,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FrameExtractedInfo sse_decode_frame_extracted_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_frameNumber = sse_decode_u_64(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    var var_jpegData = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return FrameExtractedInfo(
      timestampMs: var_timestampMs,
      frameNumber: var_frameNumber,
      confidence: var_confidence,
      jpegData: var_jpegData,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FrameExtractedInfo> sse_decode_list_frame_extracted_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FrameExtractedInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frame_extracted_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<YFrameData> sse_decode_list_y_frame_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <YFrameData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_y_frame_data(deserializer));
    }
    return ans_;
  }

  @protected
  NoteType sse_decode_note_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NoteType.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  XhsVideo? sse_decode_opt_box_autoadd_xhs_video(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_xhs_video(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  XhsApiError sse_decode_xhs_api_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_errorType = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return XhsApiError(errorType: var_errorType, message: var_message);
  }

  @protected
  XhsArticle sse_decode_xhs_article(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_desc = sse_decode_String(deserializer);
    var var_author = sse_decode_xhs_author(deserializer);
    var var_images = sse_decode_list_String(deserializer);
    var var_video = sse_decode_opt_box_autoadd_xhs_video(deserializer);
    var var_noteType = sse_decode_note_type(deserializer);
    return XhsArticle(
      title: var_title,
      desc: var_desc,
      author: var_author,
      images: var_images,
      video: var_video,
      noteType: var_noteType,
    );
  }

  @protected
  XhsAuthor sse_decode_xhs_author(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nickname = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_avatar = sse_decode_String(deserializer);
    return XhsAuthor(
      nickname: var_nickname,
      userId: var_userId,
      avatar: var_avatar,
    );
  }

  @protected
  XhsVideo sse_decode_xhs_video(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_duration = sse_decode_i_64(deserializer);
    var var_cover = sse_decode_String(deserializer);
    var var_playUrl = sse_decode_String(deserializer);
    return XhsVideo(
      duration: var_duration,
      cover: var_cover,
      playUrl: var_playUrl,
    );
  }

  @protected
  YFrameData sse_decode_y_frame_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_yPlane = sse_decode_list_prim_u_8_strict(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_frameNumber = sse_decode_u_64(deserializer);
    return YFrameData(
      width: var_width,
      height: var_height,
      yPlane: var_yPlane,
      timestampMs: var_timestampMs,
      frameNumber: var_frameNumber,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    AudioError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    AudioRecognizer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioRecognizerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    VideoFrameExtractor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VideoFrameExtractorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    AudioRecognizer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioRecognizerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    VideoFrameExtractor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VideoFrameExtractorImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioError(
    AudioError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAudioRecognizer(
    AudioRecognizer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AudioRecognizerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVideoFrameExtractor(
    VideoFrameExtractor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as VideoFrameExtractorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_xhs_video(
    XhsVideo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_xhs_video(self, serializer);
  }

  @protected
  void sse_encode_extraction_stats(
    ExtractionStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.processedFrames, serializer);
    sse_encode_u_64(self.extractedFrames, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_frame_extracted_info(
    FrameExtractedInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_u_64(self.frameNumber, serializer);
    sse_encode_f_32(self.confidence, serializer);
    sse_encode_list_prim_u_8_strict(self.jpegData, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_frame_extracted_info(
    List<FrameExtractedInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frame_extracted_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_y_frame_data(
    List<YFrameData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_y_frame_data(item, serializer);
    }
  }

  @protected
  void sse_encode_note_type(NoteType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_xhs_video(
    XhsVideo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_xhs_video(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_xhs_api_error(XhsApiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.errorType, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_xhs_article(XhsArticle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.desc, serializer);
    sse_encode_xhs_author(self.author, serializer);
    sse_encode_list_String(self.images, serializer);
    sse_encode_opt_box_autoadd_xhs_video(self.video, serializer);
    sse_encode_note_type(self.noteType, serializer);
  }

  @protected
  void sse_encode_xhs_author(XhsAuthor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nickname, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.avatar, serializer);
  }

  @protected
  void sse_encode_xhs_video(XhsVideo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.duration, serializer);
    sse_encode_String(self.cover, serializer);
    sse_encode_String(self.playUrl, serializer);
  }

  @protected
  void sse_encode_y_frame_data(YFrameData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.yPlane, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_u_64(self.frameNumber, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AudioErrorImpl extends RustOpaque implements AudioError {
  // Not to be used by end users
  AudioErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AudioErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AudioError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioErrorPtr,
  );
}

@sealed
class AudioRecognizerImpl extends RustOpaque implements AudioRecognizer {
  // Not to be used by end users
  AudioRecognizerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AudioRecognizerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AudioRecognizer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioRecognizer,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AudioRecognizerPtr,
  );

  /// 获取模型目录
  String get modelsDir =>
      RustLib.instance.api.crateApiAudioAudioRecognizerModelsDir(that: this);

  /// 转录音频文件（WAV 格式）
  Future<String> transcribeAudio({required String path, String? language}) =>
      RustLib.instance.api.crateApiAudioAudioRecognizerTranscribeAudio(
        that: this,
        path: path,
        language: language,
      );
}

@sealed
class VideoFrameExtractorImpl extends RustOpaque
    implements VideoFrameExtractor {
  // Not to be used by end users
  VideoFrameExtractorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VideoFrameExtractorImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_VideoFrameExtractor,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_VideoFrameExtractor,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_VideoFrameExtractorPtr,
  );

  /// 批量处理帧（智能去重）
  Future<List<FrameExtractedInfo>> processBatch({
    required List<YFrameData> frames,
  }) => RustLib.instance.api.crateApiVideoVideoFrameExtractorProcessBatch(
    that: this,
    frames: frames,
  );

  /// 重置状态
  void reset() =>
      RustLib.instance.api.crateApiVideoVideoFrameExtractorReset(that: this);

  /// 获取提取统计
  ExtractionStats get stats =>
      RustLib.instance.api.crateApiVideoVideoFrameExtractorStats(that: this);
}
