// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 提取统计
class ExtractionStats {
  final BigInt processedFrames;
  final BigInt extractedFrames;

  const ExtractionStats({
    required this.processedFrames,
    required this.extractedFrames,
  });

  @override
  int get hashCode => processedFrames.hashCode ^ extractedFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractionStats &&
          runtimeType == other.runtimeType &&
          processedFrames == other.processedFrames &&
          extractedFrames == other.extractedFrames;
}

/// 帧提取信息
class FrameExtractedInfo {
  final BigInt timestampMs;
  final BigInt frameNumber;
  final double confidence;
  final Uint8List jpegData;
  final int width;
  final int height;

  const FrameExtractedInfo({
    required this.timestampMs,
    required this.frameNumber,
    required this.confidence,
    required this.jpegData,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      frameNumber.hashCode ^
      confidence.hashCode ^
      jpegData.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameExtractedInfo &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          frameNumber == other.frameNumber &&
          confidence == other.confidence &&
          jpegData == other.jpegData &&
          width == other.width &&
          height == other.height;
}

/// Y 平面帧数据
class YFrameData {
  final int width;
  final int height;
  final Uint8List yPlane;
  final BigInt timestampMs;
  final BigInt frameNumber;

  const YFrameData({
    required this.width,
    required this.height,
    required this.yPlane,
    required this.timestampMs,
    required this.frameNumber,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      yPlane.hashCode ^
      timestampMs.hashCode ^
      frameNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YFrameData &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          yPlane == other.yPlane &&
          timestampMs == other.timestampMs &&
          frameNumber == other.frameNumber;
}
