// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state_machine.dart';

class ExtractionConfig {
  final StateConfig stateConfig;
  final double diffThreshold;
  final int dedupThreshold;

  const ExtractionConfig({
    required this.stateConfig,
    required this.diffThreshold,
    required this.dedupThreshold,
  });

  @override
  int get hashCode =>
      stateConfig.hashCode ^ diffThreshold.hashCode ^ dedupThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractionConfig &&
          runtimeType == other.runtimeType &&
          stateConfig == other.stateConfig &&
          diffThreshold == other.diffThreshold &&
          dedupThreshold == other.dedupThreshold;
}
