// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class StateConfig {
  final int initialSkip;
  final int maxSkip;
  final int minLockFrames;
  final int cooldownFrames;

  const StateConfig({
    required this.initialSkip,
    required this.maxSkip,
    required this.minLockFrames,
    required this.cooldownFrames,
  });

  @override
  int get hashCode =>
      initialSkip.hashCode ^
      maxSkip.hashCode ^
      minLockFrames.hashCode ^
      cooldownFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StateConfig &&
          runtimeType == other.runtimeType &&
          initialSkip == other.initialSkip &&
          maxSkip == other.maxSkip &&
          minLockFrames == other.minLockFrames &&
          cooldownFrames == other.cooldownFrames;
}
