// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ImageItem`, `NoteDetail`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 笔记类型枚举
enum NoteType {
  /// 纯视频笔记
  video,

  /// 纯图片笔记
  images,

  /// 视频 + 图片混合
  mixed,

  /// 纯文本笔记
  text;

  static Future<NoteType> default_() =>
      RustLib.instance.api.crateApiModelsXhsNoteTypeDefault();
}

class XhsArticle {
  final String title;
  final String desc;
  final XhsAuthor author;
  final List<String> images;
  final XhsVideo? video;

  /// 笔记类型，自动推断
  final NoteType noteType;

  const XhsArticle({
    required this.title,
    required this.desc,
    required this.author,
    required this.images,
    this.video,
    required this.noteType,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      desc.hashCode ^
      author.hashCode ^
      images.hashCode ^
      video.hashCode ^
      noteType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XhsArticle &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          desc == other.desc &&
          author == other.author &&
          images == other.images &&
          video == other.video &&
          noteType == other.noteType;
}

class XhsAuthor {
  final String nickname;
  final String userId;
  final String avatar;

  const XhsAuthor({
    required this.nickname,
    required this.userId,
    required this.avatar,
  });

  @override
  int get hashCode => nickname.hashCode ^ userId.hashCode ^ avatar.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XhsAuthor &&
          runtimeType == other.runtimeType &&
          nickname == other.nickname &&
          userId == other.userId &&
          avatar == other.avatar;
}

class XhsVideo {
  final PlatformInt64 duration;
  final String cover;
  final String playUrl;

  const XhsVideo({
    required this.duration,
    required this.cover,
    required this.playUrl,
  });

  @override
  int get hashCode => duration.hashCode ^ cover.hashCode ^ playUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XhsVideo &&
          runtimeType == other.runtimeType &&
          duration == other.duration &&
          cover == other.cover &&
          playUrl == other.playUrl;
}
