// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/audio/error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_timestamp`

void initSherpa({required String modelPath}) =>
    RustLib.instance.api.crateApiAudioInitSherpa(modelPath: modelPath);

void initVad({required String vadModelPath}) =>
    RustLib.instance.api.crateApiAudioInitVad(vadModelPath: vadModelPath);

Future<String> transcribeAudio({required String path, String? language}) =>
    RustLib.instance.api.crateApiAudioTranscribeAudio(
      path: path,
      language: language,
    );

Future<String> transcribePcm({
  required List<double> pcm,
  required int sampleRate,
  String? language,
}) => RustLib.instance.api.crateApiAudioTranscribePcm(
  pcm: pcm,
  sampleRate: sampleRate,
  language: language,
);
