// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/video/pipeline.dart';
import '../core/video/state_machine.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyze_region`, `compress_to_jpeg`, `crop_y_plane`, `has_region_changed`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CroppedYPlane`, `RegionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

ExtractionConfig createHighMotionConfig() =>
    RustLib.instance.api.crateApiVideoCreateHighMotionConfig();

ExtractionConfig createLowMotionConfig() =>
    RustLib.instance.api.crateApiVideoCreateLowMotionConfig();

/// 裁剪并缩放 YUV 帧（用于多模态模型输入）
///
/// 针对9:16竖屏视频：
/// - 裁掉顶部15%（标题/水印区）
/// - 裁掉底部20%（字幕/水印区）
/// - 保留中间65%（菜谱核心内容）
/// - 缩放到512x512（省Token）
CroppedFrame cropAndResizeFrame({
  required List<int> yPlane,
  required List<int> uPlane,
  required List<int> vPlane,
  required int width,
  required int height,
  required BigInt timestampMs,
  required BigInt frameNumber,
}) => RustLib.instance.api.crateApiVideoCropAndResizeFrame(
  yPlane: yPlane,
  uPlane: uPlane,
  vPlane: vPlane,
  width: width,
  height: height,
  timestampMs: timestampMs,
  frameNumber: frameNumber,
);

/// 带自定义配置的裁剪缩放
CroppedFrame cropAndResizeFrameWithConfig({
  required List<int> yPlane,
  required List<int> uPlane,
  required List<int> vPlane,
  required int width,
  required int height,
  required BigInt timestampMs,
  required BigInt frameNumber,
  required FrameCropConfig config,
}) => RustLib.instance.api.crateApiVideoCropAndResizeFrameWithConfig(
  yPlane: yPlane,
  uPlane: uPlane,
  vPlane: vPlane,
  width: width,
  height: height,
  timestampMs: timestampMs,
  frameNumber: frameNumber,
  config: config,
);

/// 批量裁剪缩放（并行处理）
Future<List<CroppedFrame>> cropAndResizeBatch({
  required List<YuvFrameData> frames,
  required FrameCropConfig config,
}) => RustLib.instance.api.crateApiVideoCropAndResizeBatch(
  frames: frames,
  config: config,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FrameExtractorManager>>
abstract class FrameExtractorManager implements RustOpaqueInterface {
  ExtractionStats getStats();

  factory FrameExtractorManager() =>
      RustLib.instance.api.crateApiVideoFrameExtractorManagerNew();

  /// 异步批量处理 - 智能文字状态去重
  /// 策略：先裁剪缩放，再判断"有没有文字"，再判断"文字变没变"
  Future<List<FrameExtractedInfo>> processBatch({
    required List<YFrameData> frames,
  });

  FrameExtractedInfo? processFrame({
    required int width,
    required int height,
    required List<int> rgbaData,
    required BigInt timestampMs,
    required BigInt frameNumber,
  });

  FrameExtractedInfo? processYFrame({
    required int width,
    required int height,
    required List<int> yPlane,
    required BigInt timestampMs,
    required BigInt frameNumber,
  });

  FrameExtractedInfo? processYuvFrame({
    required int width,
    required int height,
    required List<int> yPlane,
    required List<int> uPlane,
    required List<int> vPlane,
    required BigInt timestampMs,
    required BigInt frameNumber,
  });

  void reset();

  static FrameExtractorManager withMockDetector({
    required Uint64List textFrames,
  }) => RustLib.instance.api.crateApiVideoFrameExtractorManagerWithMockDetector(
    textFrames: textFrames,
  );
}

/// 裁剪后的帧数据（用于输出给多模态模型）
class CroppedFrame {
  /// 裁剪缩放后的 RGB 数据 (512*512*3 = 786432 bytes)
  final Uint8List rgbData;

  /// 宽度（固定512）
  final int width;

  /// 高度（固定512）
  final int height;

  /// 原始时间戳
  final BigInt timestampMs;

  /// 原始帧编号
  final BigInt frameNumber;

  const CroppedFrame({
    required this.rgbData,
    required this.width,
    required this.height,
    required this.timestampMs,
    required this.frameNumber,
  });

  @override
  int get hashCode =>
      rgbData.hashCode ^
      width.hashCode ^
      height.hashCode ^
      timestampMs.hashCode ^
      frameNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CroppedFrame &&
          runtimeType == other.runtimeType &&
          rgbData == other.rgbData &&
          width == other.width &&
          height == other.height &&
          timestampMs == other.timestampMs &&
          frameNumber == other.frameNumber;
}

class ExtractionStats {
  final BigInt processedFrames;
  final BigInt extractedFrames;

  const ExtractionStats({
    required this.processedFrames,
    required this.extractedFrames,
  });

  @override
  int get hashCode => processedFrames.hashCode ^ extractedFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractionStats &&
          runtimeType == other.runtimeType &&
          processedFrames == other.processedFrames &&
          extractedFrames == other.extractedFrames;
}

/// 帧裁剪配置（针对9:16竖屏视频优化）
class FrameCropConfig {
  /// 顶部裁剪比例 (0.0-1.0)，默认 0.15 (15%)
  final double topCropRatio;

  /// 底部裁剪比例 (0.0-1.0)，默认 0.20 (20%)
  final double bottomCropRatio;

  /// 输出尺寸（正方形），默认 512
  final int outputSize;

  const FrameCropConfig({
    required this.topCropRatio,
    required this.bottomCropRatio,
    required this.outputSize,
  });

  static Future<FrameCropConfig> default_() =>
      RustLib.instance.api.crateApiVideoFrameCropConfigDefault();

  @override
  int get hashCode =>
      topCropRatio.hashCode ^ bottomCropRatio.hashCode ^ outputSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameCropConfig &&
          runtimeType == other.runtimeType &&
          topCropRatio == other.topCropRatio &&
          bottomCropRatio == other.bottomCropRatio &&
          outputSize == other.outputSize;
}

class FrameExtractedInfo {
  final BigInt timestampMs;
  final BigInt frameNumber;
  final double confidence;

  /// JPEG 压缩后的图片数据
  final Uint8List jpegData;

  /// 图片宽度
  final int width;

  /// 图片高度
  final int height;

  const FrameExtractedInfo({
    required this.timestampMs,
    required this.frameNumber,
    required this.confidence,
    required this.jpegData,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      frameNumber.hashCode ^
      confidence.hashCode ^
      jpegData.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameExtractedInfo &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          frameNumber == other.frameNumber &&
          confidence == other.confidence &&
          jpegData == other.jpegData &&
          width == other.width &&
          height == other.height;
}

class YFrameData {
  final int width;
  final int height;
  final Uint8List yPlane;
  final BigInt timestampMs;
  final BigInt frameNumber;

  const YFrameData({
    required this.width,
    required this.height,
    required this.yPlane,
    required this.timestampMs,
    required this.frameNumber,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      yPlane.hashCode ^
      timestampMs.hashCode ^
      frameNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YFrameData &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          yPlane == other.yPlane &&
          timestampMs == other.timestampMs &&
          frameNumber == other.frameNumber;
}

/// 完整的 YUV 帧数据（包含 U/V 平面）
class YuvFrameData {
  final int width;
  final int height;
  final Uint8List yPlane;
  final Uint8List uPlane;
  final Uint8List vPlane;
  final BigInt timestampMs;
  final BigInt frameNumber;

  const YuvFrameData({
    required this.width,
    required this.height,
    required this.yPlane,
    required this.uPlane,
    required this.vPlane,
    required this.timestampMs,
    required this.frameNumber,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      yPlane.hashCode ^
      uPlane.hashCode ^
      vPlane.hashCode ^
      timestampMs.hashCode ^
      frameNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YuvFrameData &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          yPlane == other.yPlane &&
          uPlane == other.uPlane &&
          vPlane == other.vPlane &&
          timestampMs == other.timestampMs &&
          frameNumber == other.frameNumber;
}
