// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/video/manager.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VideoFrameExtractor>>
abstract class VideoFrameExtractor implements RustOpaqueInterface {
  /// 创建视频帧提取器（无需模型）
  static VideoFrameExtractor create() =>
      RustLib.instance.api.crateApiVideoVideoFrameExtractorCreate();

  /// 批量处理帧（智能去重）
  Future<List<FrameExtractedInfo>> processBatch({
    required List<YFrameData> frames,
  });

  /// 重置状态
  void reset();

  /// 获取提取统计
  ExtractionStats get stats;
}
