// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/xhs.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_xhs_url`, `regex_error`, `url_not_found`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

/// 从混合文本中提取小红书 URL 并解析
///
/// # 示例
/// ```ignore
/// let text = "家庭版馄饨｜早餐自制馄饨 真的太好吃了～好吃到汤都... http://xhslink.com/o/5ZMAfpDOokl 复制后打开【小红书】查看笔记！";
/// let article = parse_xhs_from_text(text)?;
/// println!("标题: {}", article.title);
/// ```
XhsArticle parseXhsFromText({required String text}) =>
    RustLib.instance.api.crateApiXhsParseXhsFromText(text: text);

/// 直接从 URL 解析小红书笔记
XhsArticle parseXhsFromUrl({required String url}) =>
    RustLib.instance.api.crateApiXhsParseXhsFromUrl(url: url);

/// 小红书 API 错误类型，FRB 友好的设计
class XhsApiError implements FrbException {
  final String errorType;
  final String message;

  const XhsApiError({required this.errorType, required this.message});

  @override
  int get hashCode => errorType.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XhsApiError &&
          runtimeType == other.runtimeType &&
          errorType == other.errorType &&
          message == other.message;
}
